#!/bin/bash

# 获取要监控的本地服务器IP地址
IP=$(hostname -I | awk '{print $1}')
echo -e "\n\033[1;32mIP地址：\033[0m $IP"

# 获取cpu总核数
cpu_num=$(grep -c "model name" /proc/cpuinfo)
echo -e "\033[1;32mCPU总核数：\033[0m $cpu_num\n"

# 获取CPU利用率
cpu_info=$(top -bn1 | grep "Cpu(s)")
cpu_user=$(echo $cpu_info | awk '{print $2}' | cut -d'%' -f1)
cpu_system=$(echo $cpu_info | awk '{print $4}' | cut -d'%' -f1)
cpu_idle=$(echo $cpu_info | awk '{print $8}' | cut -d'%' -f1)
cpu_iowait=$(echo $cpu_info | awk '{print $10}' | cut -d'%' -f1)

echo -e "\033[1;34mCPU 利用率：\033[0m"
echo -e "  \033[1;33m用户空间占用：\033[0m $cpu_user%"
echo -e "  \033[1;33m内核空间占用：\033[0m $cpu_system%"
echo -e "  \033[1;33m空闲：\033[0m $cpu_idle%"
echo -e "  \033[1;33m等待I/O：\033[0m $cpu_iowait%\n"

# 获取CPU上下文切换和中断次数
vmstat_info=$(vmstat -n 1 1 | sed -n 3p)
cpu_interrupt=$(echo $vmstat_info | awk '{print $11}')
cpu_context_switch=$(echo $vmstat_info | awk '{print $12}')

echo -e "\033[1;34mCPU 上下文切换和中断次数：\033[0m"
echo -e "  \033[1;33m中断次数：\033[0m $cpu_interrupt"
echo -e "  \033[1;33m上下文切换次数：\033[0m $cpu_context_switch\n"

# 获取CPU负载信息
cpu_load=$(uptime | awk -F'[a-z]:' '{print $2}')
cpu_load_1min=$(echo $cpu_load | awk '{print $1}' | cut -d',' -f1)
cpu_load_5min=$(echo $cpu_load | awk '{print $2}' | cut -d',' -f1)
cpu_load_15min=$(echo $cpu_load | awk '{print $3}' | cut -d',' -f1)

echo -e "\033[1;34mCPU 负载平均值：\033[0m"
echo -e "  \033[1;33m1分钟前：\033[0m $cpu_load_1min"
echo -e "  \033[1;33m5分钟前：\033[0m $cpu_load_5min"
echo -e "  \033[1;33m15分钟前：\033[0m $cpu_load_15min\n"

cpu_task_length=$(echo $vmstat_info | awk '{print $1}')
echo -e "\033[1;34mCPU 任务队列长度：\033[0m $cpu_task_length\n"

# 获取内存信息
mem_info=$(free | grep Mem)
mem_total=$(echo $mem_info | awk '{print $2}')
mem_sys_used=$(echo $mem_info | awk '{print $3}')
mem_sys_free=$(echo $mem_info | awk '{print $4}')

echo -e "\033[1;34m内存信息：\033[0m"
echo -e "  \033[1;33m物理内存总量：\033[0m $((mem_total / 1024)) MB"
echo -e "  \033[1;33m已使用内存总量(操作系统)：\033[0m $((mem_sys_used / 1024)) MB"
echo -e "  \033[1;33m剩余内存总量(操作系统)：\033[0m $((mem_sys_free / 1024)) MB\n"

mem_user_info=$(free | grep -A 1 Mem | tail -n 1)
mem_user_used=$(echo $mem_user_info | awk '{print $3}')
mem_user_free=$(echo $mem_user_info | awk '{print $4}')

echo -e "  \033[1;33m已使用内存总量(应用程序)：\033[0m $((mem_user_used / 1024)) MB"
echo -e "  \033[1;33m剩余内存总量(应用程序)：\033[0m $((mem_user_free / 1024)) MB\n"

mem_swap_info=$(free | grep Swap)
mem_swap_total=$(echo $mem_swap_info | awk '{print $2}')
mem_swap_used=$(echo $mem_swap_info | awk '{print $3}')
mem_swap_free=$(echo $mem_swap_info | awk '{print $4}')

echo -e "  \033[1;33m交换分区总大小：\033[0m $((mem_swap_total / 1024)) MB"
echo -e "  \033[1;33m已使用交换分区大小：\033[0m $((mem_swap_used / 1024)) MB"
echo -e "  \033[1;33m剩余交换分区大小：\033[0m $((mem_swap_free / 1024)) MB\n"

# 获取磁盘I/O统计信息
echo -e "\033[1;34m指定设备(/dev/sda)的统计信息：\033[0m"
disk_info=$(iostat -kx | grep sda)
disk_sda_rs=$(echo $disk_info | awk '{print $4}')
disk_sda_ws=$(echo $disk_info | awk '{print $5}')
disk_sda_avgqu_sz=$(echo $disk_info | awk '{print $9}')
disk_sda_await=$(echo $disk_info | awk '{print $10}')
disk_sda_svctm=$(echo $disk_info | awk '{print $11}')
disk_sda_util=$(echo $disk_info | awk '{print $12}')

echo -e "  \033[1;33m每秒向设备发起的读请求次数：\033[0m $disk_sda_rs"
echo -e "  \033[1;33m每秒向设备发起的写请求次数：\033[0m $disk_sda_ws"
echo -e "  \033[1;33m向设备发起的I/O请求队列长度平均值：\033[0m $disk_sda_avgqu_sz"
echo -e "  \033[1;33m每次向设备发起的I/O请求平均时间：\033[0m $disk_sda_await ms"
echo -e "  \033[1;33m向设备发起的I/O服务时间均值：\033[0m $disk_sda_svctm ms"
echo -e "  \033[1;33m向设备发起I/O请求的CPU时间百分占比：\033[0m $disk_sda_util%\n"